#!/bin/sh -e
INITRD=${INITRD:-"No"}
export INITRD
if [ -d "/etc/kernel/prerm.d" ]; then
  run-parts -v --report --exit-on-error --arg=4.19.25-v8-78eb13b25d5e-bis+ --arg=/boot/kernel8.img /etc/kernel/prerm.d
fi
if [ -d "/etc/kernel/prerm.d/4.19.25-v8-78eb13b25d5e-bis+" ]; then
  run-parts -v --report --exit-on-error --arg=4.19.25-v8-78eb13b25d5e-bis+ --arg=/boot/kernel8.img /etc/kernel/prerm.d/4.19.25-v8-78eb13b25d5e-bis+
fi
#DEBHELPER#
